---

# Manage Collectd install on Debian systems

- name: 'INSTALL | APT | Install system dependencies'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: True
    cache_valid_time: "{{ collectd_repository_cache_valid_time }}"
  with_items: "{{ collectd_system_dependencies }}"


- name: 'INSTALL | APT | Install additional repository gpg key'
  apt_key:
    id: "{{ item.id }}"
    keyserver: "{{ item.keyserver }}"
  with_items: "{{ collectd_repositories_keys }}"
  when: "collectd_use_additional_repository | bool"


- name: 'INSTALL | APT | Install additional repository'
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: True
  with_items: "{{ collectd_repositories }}"
  when: "collectd_use_additional_repository | bool"


- name: 'INSTALL | APT | Install collectd'
  apt:
    name: "{{ item }}"
    state: "{{ collectd_package_state }}"
    cache_valid_time: "{{ collectd_repository_cache_valid_time }}"
    update_cache: "{{ collectd_repository_update_cache }}"
  with_items: "{{ collectd_packages }}"
  notify: 'HANDLER | Restart collectd'


- name: 'INSTALL | APT | Install collectd plugins dependencies'
  apt:
    name: "{{ item }}"
    state: "{{ collectd_package_state }}"
    cache_valid_time: "{{ collectd_repository_cache_valid_time }}"
    update_cache: "{{ collectd_repository_update_cache }}"
  with_items: "{{ collectd_plugins_with_dependencies
                  | map('extract', collectd_plugins_dependencies)
                  | list }}"
  when: "(collectd_plugins_dependencies | length) > 0"
  notify: 'HANDLER | Restart collectd'
