---

# Main tasks file for collectd role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::collectd'
    - 'role::collectd::config'
    - 'role::collectd::init'
    - 'role::collectd::install'


- name: 'INSTALL | Manage OS family installation tasks'
  become: True
  include: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::collectd'
    - 'role::collectd::install'


- name: 'SERVICE | Manage collectd service'
  become: True
  service:
    name: "{{ collectd_service_name }}"
    enabled: "{{ collectd_service_enabled }}"
    state: "{{ collectd_service_state }}"
  notify:
    - 'HANDLER | Restart collectd'
  tags:
    - 'role::collectd'
    - 'role::collectd::install'


- name: 'CONFIG | Manage collectd configuration tasks'
  become: True
  include: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'role::collectd'
    - 'role::collectd::config'
