---

# Main tasks file for collectd role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::collectd'
    - 'role::collectd::init'


- include: 'install_debian.yml'
  when: "{{ ansible_os_family == 'Debian' }}"
  tags:
    - 'install'
    - 'collectd'


- name: 'Manage collectd service'
  become: True
  service:
    name: "{{ collectd_service_name }}"
    enabled: "{{ collectd_service_enabled }}"
    state: "{{ collectd_service_state }}"
  notify:
    - 'restart collectd'
  tags:
    - 'install'
    - 'collectd'


- name: 'Manage collectd configuration tasks'
  include: 'configure.yml'
  tags:
    - 'configure'
    - 'collectd'
